
const Videos = [
	{
		id: "1",
        title: 'Culto Vesperal | Sede Central - 11/12/2023',
        url_image: 'https://imgs.search.brave.com/gXSd4Y04W45MH7wMAKbdhZi5EZypFleFSWn1oRnNENA/rs:fit:1200:720:1/g:ce/aHR0cHM6Ly9pLnl0/aW1nLmNvbS92aS9R/Q3pUZ1VxdmZiYy9t/YXhyZXNkZWZhdWx0/LmpwZw',
        url: '9cwhRH2nPm0',
        category: 'culto_vesperal',
        createdAt: '11/12/2023',
	},
    {
		id: '2',
        title: 'Culto Vesperal | "As diversas situações após a morte" (2ª parte) - 27/10/2023',
        url_image: 'https://imgs.search.brave.com/gXSd4Y04W45MH7wMAKbdhZi5EZypFleFSWn1oRnNENA/rs:fit:1200:720:1/g:ce/aHR0cHM6Ly9pLnl0/aW1nLmNvbS92aS9R/Q3pUZ1VxdmZiYy9t/YXhyZXNkZWZhdWx0/LmpwZw',
        url: 'Twljv8Em2WA',
        category: 'culto_vesperal',
        createdAt: '27/10/2023',
	},
    {
		id: '3',
        title: 'Culto Vesperal | "As três calamidades maiores e as três calamidades menores" (2ª parte) - 07/12/2023',
        url_image: 'https://imgs.search.brave.com/gXSd4Y04W45MH7wMAKbdhZi5EZypFleFSWn1oRnNENA/rs:fit:1200:720:1/g:ce/aHR0cHM6Ly9pLnl0/aW1nLmNvbS92aS9R/Q3pUZ1VxdmZiYy9t/YXhyZXNkZWZhdWx0/LmpwZw',
        url: 'olJkVbxhZTU',
        category: 'culto_vesperal',
        createdAt: '07/12/2023',
	},
    {
		id: '4',
        title: 'Culto Vesperal | "Mundo semicivilizado e semisselvagem" (1ª parte) - 22/09/2023',
        url_image: 'https://imgs.search.brave.com/gXSd4Y04W45MH7wMAKbdhZi5EZypFleFSWn1oRnNENA/rs:fit:1200:720:1/g:ce/aHR0cHM6Ly9pLnl0/aW1nLmNvbS92aS9R/Q3pUZ1VxdmZiYy9t/YXhyZXNkZWZhdWx0/LmpwZw',
        url: 'uQhWuygu3js',
        category: 'culto_vesperal',
        createdAt: '22/09/2023',
	},
    {
		id:' 5',
        title: 'Culto Vesperal | "As três calamidades maiores e as três calamidades menores" (3ª parte) - 08/12/2023',
        url_image: 'https://imgs.search.brave.com/gXSd4Y04W45MH7wMAKbdhZi5EZypFleFSWn1oRnNENA/rs:fit:1200:720:1/g:ce/aHR0cHM6Ly9pLnl0/aW1nLmNvbS92aS9R/Q3pUZ1VxdmZiYy9t/YXhyZXNkZWZhdWx0/LmpwZw',
        url: 'DnwqAl1y1XA',
        category: 'culto_vesperal',
        createdAt: '08/12/2023',
	},
    {
		id: '6',
        title: 'Culto Vesperal | Sede Central - 21/02/2023',
        url_image: 'https://imgs.search.brave.com/gXSd4Y04W45MH7wMAKbdhZi5EZypFleFSWn1oRnNENA/rs:fit:1200:720:1/g:ce/aHR0cHM6Ly9pLnl0/aW1nLmNvbS92aS9R/Q3pUZ1VxdmZiYy9t/YXhyZXNkZWZhdWx0/LmpwZw',
        url: '',
        category: 'culto_vesperal',
        createdAt: '21/02/2023',
	},
    {
		id: '7',
        title: 'Culto Vesperal | "A respeito dos telegramas de pedidos de graça" - 05/12/2023',
        url_image: 'https://imgs.search.brave.com/gXSd4Y04W45MH7wMAKbdhZi5EZypFleFSWn1oRnNENA/rs:fit:1200:720:1/g:ce/aHR0cHM6Ly9pLnl0/aW1nLmNvbS92aS9R/Q3pUZ1VxdmZiYy9t/YXhyZXNkZWZhdWx0/LmpwZw',
        url: 'OnNsYFNK32M',
        category: 'culto_vesperal',
        createdAt: '05/12/2023',
	},
    {
		id: '8',
        title: 'Culto Vesperal | "Força absoluta" (3ª parte) - 03/12/2023',
        url_image: 'https://imgs.search.brave.com/gXSd4Y04W45MH7wMAKbdhZi5EZypFleFSWn1oRnNENA/rs:fit:1200:720:1/g:ce/aHR0cHM6Ly9pLnl0/aW1nLmNvbS92aS9R/Q3pUZ1VxdmZiYy9t/YXhyZXNkZWZhdWx0/LmpwZw',
        url: 'vAJne6upfWQ',
        category: 'culto_vesperal',
        createdAt: '03/12/2023',
	},
    {
		id: '9',
        title: 'Culto Vesperal | "As três calamidades maiores e as três calamidades menores" (4ª parte) - 09/12/2023',
        url_image: 'https://imgs.search.brave.com/gXSd4Y04W45MH7wMAKbdhZi5EZypFleFSWn1oRnNENA/rs:fit:1200:720:1/g:ce/aHR0cHM6Ly9pLnl0/aW1nLmNvbS92aS9R/Q3pUZ1VxdmZiYy9t/YXhyZXNkZWZhdWx0/LmpwZw',
        url: '3Yu3-GdK8sI',
        category: 'culto_vesperal',
        createdAt: '09/12/2023',
	},
    {
		id: '10',
        title: 'Culto Vesperal | "As três calamidades maiores e as três calamidades menores" (1ª parte) - 06/12/2023',
        url_image: 'https://imgs.search.brave.com/gXSd4Y04W45MH7wMAKbdhZi5EZypFleFSWn1oRnNENA/rs:fit:1200:720:1/g:ce/aHR0cHM6Ly9pLnl0/aW1nLmNvbS92aS9R/Q3pUZ1VxdmZiYy9t/YXhyZXNkZWZhdWx0/LmpwZw',
        url: 'gmP2eb5gqvI&t=35s',
        category: 'culto_vesperal',
        createdAt: '06/12/2023',
	},
    {
		id: "11",
        title: 'Culto Matinal | Sede Central - 12/12/2023',
        url_image: 'https://i.ytimg.com/vi/PF249gShdf8/maxresdefault.jpg',
        url: 'gmP2eb5gqvI&t=140s',
        category: 'culto_matinal',
        createdAt: '12/12/2023',
	},
    {
		id: '12',
        title: 'Culto Matinal | Sede Central - 11/12/2023',
        url_image: 'https://i.ytimg.com/vi/PF249gShdf8/maxresdefault.jpg',
        url: 'EoBdc4VJGGY',
        category: 'culto_matinal',
        createdAt: '11/12/2023',
	},
    {
		id: '13',
        title: 'Culto Matinal | "A reencarnação" (1ª parte) - 06/11/2023',
        url_image: 'https://i.ytimg.com/vi/PF249gShdf8/maxresdefault.jpg',
        url: 'GcmGlPPoSHU',
        category: 'culto_matinal',
        createdAt: '06/11/2023',
	},
    {
		id: '14',
        title: 'Culto Matinal | "As três calamidades maiores e as três calamidades menores" (2ª parte) - 07/12/2023',
        url_image: 'https://i.ytimg.com/vi/PF249gShdf8/maxresdefault.jpg',
        url: 'TKha4RubFYs',
        category: 'culto_matinal',
        createdAt: '07/12/2023',
	},
    {
		id:'15',
        title: 'Culto Matinal | "As três calamidades maiores e as três calamidades menores" (1ª parte) - 06/12/2023',
        url_image: 'https://i.ytimg.com/vi/PF249gShdf8/maxresdefault.jpg',
        url: 'ZIRl2qWARDg',
        category: 'culto_matinal',
        createdAt: '06/12/2023',
	},
    {
		id: '16',
        title: 'Culto Matinal | "Força absoluta" (3ª parte) - 03/12/2023',
        url_image: 'https://i.ytimg.com/vi/PF249gShdf8/maxresdefault.jpg',
        url: 'tPduhP4hjNE',
        category: 'culto_matinal',
        createdAt: '03/12/2023',
	},
    {
		id: '17',
        title: 'Culto Matinal | "Pessoas medrosas" - 23/11/2023',
        url_image: 'https://i.ytimg.com/vi/PF249gShdf8/maxresdefault.jpg',
        url: 'EVIpC5vhKNk',
        category: 'culto_matinal',
        createdAt: '23/11/2023',
	},
    {
		id: '18',
        title: 'Culto Matinal | "As diversas situações após a morte" (3ª parte) - 28/10/2023',
        url_image: 'https://i.ytimg.com/vi/PF249gShdf8/maxresdefault.jpg',
        url: 'DskiSZcCXc8',
        category: 'culto_matinal',
        createdAt: '28/10/2023',
	},
    {
		id: '20',
        title: 'Culto Matinal | "Julgamento no Mundo Espiritual" (2ª parte) - 09/11/2023',
        url_image: 'https://i.ytimg.com/vi/PF249gShdf8/maxresdefault.jpg',
        url: 'JA3hVeY5ytY',
        category: 'culto_vesperal',
        createdAt: '09/11/2023',
	},
    {
		id: "21",
        title: 'Culto Mensal de Agradecimento dedicado à Coluna do Belo | Solo Sagrado - 03/09/2023',
        url_image: 'https://i.ytimg.com/vi/7gxD0Xhbb7s/maxresdefault.jpg',
        url: 'U99n9F9TucY',
        category: 'culto_solo',
        createdAt: '03/09/2023',
	},
    {
		id: '22',
        title: 'Culto Mensal de Agradecimento dedicado à Coluna da Agricultura Natural | Solo Sagrado - 07/08/2022',
        url_image: 'https://i.ytimg.com/vi/hQhNezrLckQ/maxresdefault.jpg',
        url: 'hQhNezrLckQ&t=3615s',
        category: 'culto_solo',
        createdAt: '07/08/2022',
	},
    {
		id: '23',
        title: 'Culto Mensal de Agradecimento dedicado aos pioneiros | Solo Sagrado de Guarapiranga - 01/05/2023',
        url_image: 'https://i.ytimg.com/vi/89A8Cgv_hEA/maxresdefault.jpg',
        url: '89A8Cgv_hEA',
        category: 'culto_solo',
        createdAt: '01/05/2023',
	},
    {
		id: '24',
        title: 'Culto Mensal de Agradecimento de Março | Solo Sagrado de Guarapiranga - 06/03/2022',
        url_image: 'https://i.ytimg.com/vi/M1Ze2BAcCgc/maxresdefault.jpg',
        url: 'M1Ze2BAcCgc',
        category: 'culto_solo',
        createdAt: '06/03/2022',
	},
    {
		id:'25',
        title: 'Culto Mensal de Agradecimento do mês de outubro | Solo Sagrado - 01/10/2022',
        url_image: 'https://i.ytimg.com/vi/I77_nLw0X3U/maxresdefault.jpg',
        url: 'I77_nLw0X3U',
        category: 'culto_solo',
        createdAt: '01/10/2022',
	},
    {
		id: '26',
        title: 'Culto Mensal de Agradecimento de Outubro - Solo Sagrado de Guarapiranga - 04/10/2020',
        url_image: 'https://i.ytimg.com/vi/WgrNF-BO7tk/maxresdefault.jpg',
        url: 'WgrNF-BO7tk',
        category: 'culto_solo',
        createdAt: '04/10/2020',
	},
    {
		id: '27',
        title: 'Culto Mensal de Agradecimento de Fevereiro | Solo Sagrado de Guarapiranga - 06/02/2022',
        url_image: 'https://th.bing.com/th/id/OIP.1R0FFpj-QesosSftIm6zEQAAAA?rs=1&pid=ImgDetMain',
        url: 'WSeMS_O700o',
        category: 'culto_solo',
        createdAt: '06/02/2022',
	},
    {
		id: '28',
        title: 'Culto Mensal de Agradecimento dedicado aos jovens 2023 | Solo Sagrado de Guarapiranga - 02/04/2023',
        url_image: 'https://i.ytimg.com/vi/mJze2BJ-2wY/maxresdefault_live.jpg',
        url: 'mJze2BJ-2wY',
        category: 'culto_solo',
        createdAt: '02/04/2023',
	},

    {
		id: '29',
        title: 'Culto Mensal de Agradecimento, dedicado à Coluna do Belo - 06/09/2020',
        url_image: 'https://i.ytimg.com/vi/Kt3R0cpa15I/maxresdefault.jpg',
        url: 'Kt3R0cpa15I',
        category: 'culto_solo',
        createdAt: '06/09/2020',
	},
    {
		id: '30',
        title: 'Culto Mensal de Agradecimento de Março | Solo Sagrado de Guarapiranga - 05/03/2023',
        url_image: 'https://i.ytimg.com/vi/UlQ2mpgeqsw/maxresdefault.jpg',
        url: 'UlQ2mpgeqsw',
        category: 'culto_solo',
        createdAt: '05/03/2023',
	},
    {
		id: "31",
        title: 'Eu Caminho com Meishu-Sama por Lila Hisae Yamakawa - Igreja Londrina',
        url_image: 'https://i.ytimg.com/vi/aiJZDwkFVwk/maxresdefault.jpg',
        url: 'aiJZDwkFVwk',
        category: 'eu_caminho',
        createdAt: '06/09/2020',
	},
    {
		id: '32',
        title: 'Eu Caminho com Meishu-Sama por Cristiane Brasil Silveira - Igreja Rio Grande do Sul',
        url_image: 'https://i.ytimg.com/vi/AP0DMcOWS0M/maxresdefault.jpg',
        url: 'AP0DMcOWS0M',
        category: 'eu_caminho',
        createdAt: '02/10/2022',
	},
    {
		id: '33',
        title: 'Eu Caminho com Meishu-Sama por Min Miriam Yuri Honma Moura - Igreja São José do Rio Preto',
        url_image: 'https://i.ytimg.com/vi/teY_eIkydAI/maxresdefault.jpg',
        url: 'teY_eIkydAI',
        category: 'eu_caminho',
        createdAt: '12/11/2022',
	},
    {
		id: '34',
        title: 'Eu Caminho com Meishu-Sama por Margarete Akiko Yamane - Igreja Lapa',
        url_image: 'https://i.ytimg.com/vi/wXtz5tuB_vU/maxresdefault.jpg',
        url: 'wXtz5tuB_vU',
        category: 'eu_caminho',
        createdAt: '02/03/2022',
	},
    {
		id:'35',
        title: 'Eu Caminho com Meishu-Sama por Sérgio Rodrigues Cassetari - Igreja Tatuapé',
        url_image: 'https://i.ytimg.com/vi/CN3p3Itp_mA/maxresdefault.jpg',
        url: 'CN3p3Itp_mA',
        category: 'eu_caminho',
        createdAt: '02/02/2023',
	},
    {
		id: '36',
        title: 'Eu Caminho com Meishu-Sama por Rosemeri da Silva Correa - Igreja Vila da Penha',
        url_image: 'https://i.ytimg.com/vi/AtS29zcypnU/maxresdefault.jpg',
        url: 'AtS29zcypnU',
        category: 'eu_caminho',
        createdAt: '12/12/2023',
	},
    {
		id: '37',
        title: 'Eu Caminho com Meishu-Sama por Eiko Helena Oda Emoto - Igreja Lapa',
        url_image: 'https://i.ytimg.com/vi/RVfwH3Yjozc/maxresdefault.jpg',
        url: 'RVfwH3Yjozc',
        category: 'eu_caminho',
        createdAt: '06/02/2022',
	},
    {
		id: '38',
        title: 'Eu Caminho com Meishu-Sama por Ernani Tavares Silva de Lira - Igreja Recife',
        url_image: 'https://i.ytimg.com/vi/A2Cmlaa-JH0/maxresdefault.jpg',
        url: 'mJze2BJ-2wY',
        category: 'eu_caminho',
        createdAt: '02/04/2023',
	},

    {
		id: '39',
        title: 'Eu Caminho com Meishu-Sama por Fellipe Santos Inácio - Igreja Brasília',
        url_image: 'https://i.ytimg.com/vi/tEYCrQOEb4Y/maxresdefault.jpg',
        url: 'tEYCrQOEb4Y',
        category: 'eu_caminho',
        createdAt: '06/09/2020',
	},
    {
		id: '40',
        title: 'Eu Caminho com Meishu-Sama por Newton Serizawa Yamanaka - Igreja Araçatuba',
        url_image: 'https://i.ytimg.com/vi/_6HhEUUyjjI/maxresdefault.jpg',
        url: '_6HhEUUyjjI',
        category: 'eu_caminho',
        createdAt: '05/03/2023',
	},
];

export default Videos;